/**
 * GENERATED by `apps/studio/gen-component-catalog.ts` from the engine's component definitions. Do not edit by hand:
 * run `npx tsx apps/studio/gen-component-catalog.ts --write`. `test-component-catalog.ts` fails while this file
 * is stale.
 *
 * The component catalog as data, so the web bundle never imports the definitions themselves (UI redesign S8.1, T1;
 * the generator's header says why). The plugin computes the same catalog live.
 */
import type { Catalog } from './component-catalog';

export const COMPONENT_CATALOG_DATA: Catalog = [
  {
    "id": "icon",
    "name": "Icon",
    "category": "foundations",
    "summary": "Glyph from the icon set at 16/20/24/32px. Decorative unless labeled; never interactive.",
    "unit": "components",
    "spacing": [],
    "buildable": true,
    "reason": null,
    "members": 44,
    "nests": []
  },
  {
    "id": "focus-ring",
    "name": "FocusRing",
    "category": "foundations",
    "summary": "Keyboard-focus ring nested by focusable components. Build first; don't place alone.",
    "unit": "variants",
    "spacing": [],
    "buildable": true,
    "reason": null,
    "members": 2,
    "nests": []
  },
  {
    "id": "button",
    "name": "Button",
    "category": "form",
    "summary": "Triggers an action in place. For navigation, use a link.",
    "unit": "variants",
    "spacing": [
      {
        "key": "size.small.padding-x",
        "ref": "space.200"
      },
      {
        "key": "size.medium.padding-x",
        "ref": "space.200"
      },
      {
        "key": "size.large.padding-x",
        "ref": "space.300"
      },
      {
        "key": "size.small.padding-x-visual",
        "ref": "space.150"
      },
      {
        "key": "size.medium.padding-x-visual",
        "ref": "space.150"
      },
      {
        "key": "size.large.padding-x-visual",
        "ref": "space.200"
      },
      {
        "key": "size.small.padding-y",
        "ref": "space.075"
      },
      {
        "key": "size.medium.padding-y",
        "ref": "space.100"
      },
      {
        "key": "size.large.padding-y",
        "ref": "space.100"
      },
      {
        "key": "size.small.gap",
        "ref": "space.100"
      },
      {
        "key": "size.medium.gap",
        "ref": "space.100"
      },
      {
        "key": "size.large.gap",
        "ref": "space.150"
      }
    ],
    "buildable": true,
    "reason": null,
    "members": 432,
    "nests": [
      "icon",
      "focus-ring",
      "spinner"
    ]
  },
  {
    "id": "button-destructive",
    "name": "Button.Destructive",
    "category": "form",
    "summary": "Triggers a destructive action — delete, remove — in the destructive color.",
    "unit": "variants",
    "spacing": [
      {
        "key": "size.small.padding-x",
        "ref": "space.200"
      },
      {
        "key": "size.medium.padding-x",
        "ref": "space.200"
      },
      {
        "key": "size.large.padding-x",
        "ref": "space.300"
      },
      {
        "key": "size.small.padding-x-visual",
        "ref": "space.150"
      },
      {
        "key": "size.medium.padding-x-visual",
        "ref": "space.150"
      },
      {
        "key": "size.large.padding-x-visual",
        "ref": "space.200"
      },
      {
        "key": "size.small.padding-y",
        "ref": "space.075"
      },
      {
        "key": "size.medium.padding-y",
        "ref": "space.100"
      },
      {
        "key": "size.large.padding-y",
        "ref": "space.100"
      },
      {
        "key": "size.small.gap",
        "ref": "space.100"
      },
      {
        "key": "size.medium.gap",
        "ref": "space.100"
      },
      {
        "key": "size.large.gap",
        "ref": "space.150"
      }
    ],
    "buildable": true,
    "reason": null,
    "members": 432,
    "nests": [
      "icon",
      "focus-ring",
      "spinner"
    ]
  },
  {
    "id": "button-neutral",
    "name": "Button.Neutral",
    "category": "form",
    "summary": "Triggers an action with no brand emphasis — toolbars, dense rows.",
    "unit": "variants",
    "spacing": [
      {
        "key": "size.small.padding-x",
        "ref": "space.200"
      },
      {
        "key": "size.medium.padding-x",
        "ref": "space.200"
      },
      {
        "key": "size.large.padding-x",
        "ref": "space.300"
      },
      {
        "key": "size.small.padding-x-visual",
        "ref": "space.150"
      },
      {
        "key": "size.medium.padding-x-visual",
        "ref": "space.150"
      },
      {
        "key": "size.large.padding-x-visual",
        "ref": "space.200"
      },
      {
        "key": "size.small.padding-y",
        "ref": "space.075"
      },
      {
        "key": "size.medium.padding-y",
        "ref": "space.100"
      },
      {
        "key": "size.large.padding-y",
        "ref": "space.100"
      },
      {
        "key": "size.small.gap",
        "ref": "space.100"
      },
      {
        "key": "size.medium.gap",
        "ref": "space.100"
      },
      {
        "key": "size.large.gap",
        "ref": "space.150"
      }
    ],
    "buildable": true,
    "reason": null,
    "members": 432,
    "nests": [
      "icon",
      "focus-ring",
      "spinner"
    ]
  },
  {
    "id": "icon-button",
    "name": "IconButton",
    "category": "form",
    "summary": "Icon-only action. Needs an accessible name.",
    "unit": "variants",
    "spacing": [],
    "buildable": true,
    "reason": null,
    "members": 216,
    "nests": [
      "icon",
      "focus-ring",
      "spinner"
    ]
  },
  {
    "id": "icon-button-destructive",
    "name": "IconButton.Destructive",
    "category": "form",
    "summary": "Icon-only destructive action. Needs an accessible name.",
    "unit": "variants",
    "spacing": [],
    "buildable": true,
    "reason": null,
    "members": 216,
    "nests": [
      "icon",
      "focus-ring",
      "spinner"
    ]
  },
  {
    "id": "icon-button-neutral",
    "name": "IconButton.Neutral",
    "category": "form",
    "summary": "Icon-only action with no brand emphasis. Needs an accessible name.",
    "unit": "variants",
    "spacing": [],
    "buildable": true,
    "reason": null,
    "members": 216,
    "nests": [
      "icon",
      "focus-ring",
      "spinner"
    ]
  },
  {
    "id": "field-label",
    "name": "FieldLabel",
    "category": "form",
    "summary": "Visible label that names a field, with an optional required marker.",
    "unit": "variants",
    "spacing": [],
    "buildable": true,
    "reason": null,
    "members": 24,
    "nests": []
  },
  {
    "id": "field-message",
    "name": "FieldMessage",
    "category": "feedback",
    "summary": "Helper or validation caption below a field; status sets its icon and ink.",
    "unit": "variants",
    "spacing": [],
    "buildable": true,
    "reason": null,
    "members": 4,
    "nests": []
  },
  {
    "id": "text-field",
    "name": "TextField",
    "category": "form",
    "summary": "Single-line text field: label, input, and helper or validation message.",
    "unit": "variants",
    "spacing": [
      {
        "key": "pad-x",
        "ref": "space.200"
      },
      {
        "key": "pad-y",
        "ref": "space.100"
      },
      {
        "key": "gap",
        "ref": "space.100"
      },
      {
        "key": "size.small.pad-x",
        "ref": "space.200"
      },
      {
        "key": "size.medium.pad-x",
        "ref": "space.200"
      },
      {
        "key": "size.large.pad-x",
        "ref": "space.300"
      },
      {
        "key": "size.small.pad-y",
        "ref": "space.075"
      },
      {
        "key": "size.medium.pad-y",
        "ref": "space.100"
      },
      {
        "key": "size.large.pad-y",
        "ref": "space.100"
      }
    ],
    "buildable": true,
    "reason": null,
    "members": 24,
    "nests": [
      "field-label",
      "icon",
      "field-message",
      "focus-ring"
    ]
  },
  {
    "id": "textarea",
    "name": "Textarea",
    "category": "form",
    "summary": "Multi-line text field: label, input area, and helper or validation message.",
    "unit": "variants",
    "spacing": [
      {
        "key": "pad-x",
        "ref": "space.200"
      },
      {
        "key": "pad-y",
        "ref": "space.100"
      },
      {
        "key": "size.small.pad-x",
        "ref": "space.200"
      },
      {
        "key": "size.medium.pad-x",
        "ref": "space.200"
      },
      {
        "key": "size.large.pad-x",
        "ref": "space.300"
      },
      {
        "key": "size.small.pad-y",
        "ref": "space.075"
      },
      {
        "key": "size.medium.pad-y",
        "ref": "space.100"
      },
      {
        "key": "size.large.pad-y",
        "ref": "space.100"
      }
    ],
    "buildable": true,
    "reason": null,
    "members": 24,
    "nests": [
      "field-label",
      "field-message",
      "focus-ring"
    ]
  },
  {
    "id": "checkbox-control",
    "name": "Checkbox.Control",
    "category": "form",
    "summary": "Checkbox box with check/dash glyph and focus ring. Nested by Checkbox.Row; no label.",
    "unit": "variants",
    "spacing": [],
    "buildable": true,
    "reason": null,
    "members": 54,
    "nests": [
      "focus-ring"
    ]
  },
  {
    "id": "checkbox-row",
    "name": "Checkbox.Row",
    "category": "form",
    "summary": "Labeled checkbox for a staged on/off choice. The whole row is the hit target.",
    "unit": "variants",
    "spacing": [
      {
        "key": "size.small.gap",
        "ref": "space.100"
      },
      {
        "key": "size.medium.gap",
        "ref": "space.100"
      },
      {
        "key": "size.large.gap",
        "ref": "space.150"
      }
    ],
    "buildable": true,
    "reason": null,
    "members": 3,
    "nests": [
      "checkbox-control"
    ]
  },
  {
    "id": "checkbox-group",
    "name": "Checkbox.Group",
    "category": "form",
    "summary": "Labeled stack of Checkbox rows. Owns the value array, required and validation.",
    "unit": "variants",
    "spacing": [],
    "buildable": true,
    "reason": null,
    "members": 3,
    "nests": [
      "field-label",
      "checkbox-row"
    ]
  },
  {
    "id": "radio-control",
    "name": "Radio.Control",
    "category": "form",
    "summary": "Outlined radio ring; dot and brand ring on select. Nested by Radio.Row; no label.",
    "unit": "variants",
    "spacing": [],
    "buildable": true,
    "reason": null,
    "members": 30,
    "nests": [
      "focus-ring"
    ]
  },
  {
    "id": "radio-row",
    "name": "Radio.Row",
    "category": "form",
    "summary": "One labeled option inside a Radio.Group. The whole row is the hit target.",
    "unit": "variants",
    "spacing": [
      {
        "key": "size.small.gap",
        "ref": "space.100"
      },
      {
        "key": "size.medium.gap",
        "ref": "space.100"
      },
      {
        "key": "size.large.gap",
        "ref": "space.150"
      }
    ],
    "buildable": true,
    "reason": null,
    "members": 3,
    "nests": [
      "radio-control"
    ]
  },
  {
    "id": "radio-group",
    "name": "Radio.Group",
    "category": "form",
    "summary": "Labeled stack of Radio rows. Owns the shared name, one value and validation.",
    "unit": "variants",
    "spacing": [],
    "buildable": true,
    "reason": null,
    "members": 3,
    "nests": [
      "field-label",
      "radio-row"
    ]
  },
  {
    "id": "switch-control",
    "name": "Switch.Control",
    "category": "form",
    "summary": "Switch track, thumb, state glyph and focus ring. Nested by Switch.Row; no label.",
    "unit": "variants",
    "spacing": [],
    "buildable": true,
    "reason": null,
    "members": 24,
    "nests": [
      "focus-ring"
    ]
  },
  {
    "id": "switch-row",
    "name": "Switch.Row",
    "category": "form",
    "summary": "Labeled switch for a setting that applies immediately. Label leads, switch trails.",
    "unit": "variants",
    "spacing": [
      {
        "key": "size.small.gap",
        "ref": "space.100"
      },
      {
        "key": "size.medium.gap",
        "ref": "space.100"
      }
    ],
    "buildable": true,
    "reason": null,
    "members": 2,
    "nests": [
      "switch-control"
    ]
  },
  {
    "id": "select",
    "name": "Select",
    "category": "form",
    "summary": "Closed control for picking one value from a known set. The menu is the platform's.",
    "unit": "variants",
    "spacing": [
      {
        "key": "pad-x",
        "ref": "space.200"
      },
      {
        "key": "pad-y",
        "ref": "space.100"
      },
      {
        "key": "gap",
        "ref": "space.100"
      }
    ],
    "buildable": true,
    "reason": null,
    "members": 24,
    "nests": [
      "field-label",
      "icon",
      "field-message",
      "focus-ring"
    ]
  },
  {
    "id": "veil",
    "name": "Veil",
    "category": "foundations",
    "summary": "Wash over media so text stays legible, solid or fading from one edge. Verify contrast.",
    "unit": "variants",
    "spacing": [],
    "buildable": true,
    "reason": null,
    "members": 30,
    "nests": []
  },
  {
    "id": "image-placeholder",
    "name": "ImagePlaceholder",
    "category": "foundations",
    "summary": "Empty media frame locked to 1:1, 4:3 or 16:9. Drop an image fill onto it.",
    "unit": "variants",
    "spacing": [],
    "buildable": true,
    "reason": null,
    "members": 3,
    "nests": []
  },
  {
    "id": "spinner",
    "name": "Spinner",
    "category": "foundations",
    "summary": "Indeterminate loading indicator on the icon ladder. Announces \"Loading\" unless its host hides it.",
    "unit": "components",
    "spacing": [],
    "buildable": true,
    "reason": null,
    "members": 4,
    "nests": []
  },
  {
    "id": "badge",
    "name": "Badge",
    "category": "foundations",
    "summary": "A static status label, count or dot. Nothing to click, and color is never the only signal.",
    "unit": "variants",
    "spacing": [],
    "buildable": true,
    "reason": null,
    "members": 20,
    "nests": []
  },
  {
    "id": "tag",
    "name": "Tag",
    "category": "foundations",
    "summary": "An interactive token a user toggles or removes. A static label is a badge.",
    "unit": "variants",
    "spacing": [
      {
        "key": "size.small.padding-x",
        "ref": "space.100"
      },
      {
        "key": "size.medium.padding-x",
        "ref": "space.150"
      },
      {
        "key": "size.large.padding-x",
        "ref": "space.200"
      },
      {
        "key": "size.small.select.gap",
        "ref": "space.075"
      },
      {
        "key": "size.medium.select.gap",
        "ref": "space.100"
      },
      {
        "key": "size.large.select.gap",
        "ref": "space.150"
      },
      {
        "key": "size.small.dismissible.visible-gap",
        "ref": "space.075"
      },
      {
        "key": "size.medium.dismissible.visible-gap",
        "ref": "space.100"
      },
      {
        "key": "size.large.dismissible.visible-gap",
        "ref": "space.100"
      },
      {
        "key": "size.small.check-gap",
        "ref": "space.050"
      },
      {
        "key": "size.medium.check-gap",
        "ref": "space.075"
      },
      {
        "key": "size.large.check-gap",
        "ref": "space.100"
      },
      {
        "key": "size.small.select.padding-end",
        "ref": "space.100"
      },
      {
        "key": "size.medium.select.padding-end",
        "ref": "space.150"
      },
      {
        "key": "size.large.select.padding-end",
        "ref": "space.200"
      }
    ],
    "buildable": true,
    "reason": null,
    "members": 45,
    "nests": [
      "icon",
      "focus-ring"
    ]
  }
];
