/**
 * CSS declaration/reference symmetry.
 *
 * The invariant this file exists to protect: every `var(--x)` the CSS exporter
 * emits must have a matching `--x:` declaration in the same output. The two
 * sides are generated by different code paths, and they silently diverged once
 * token names began preserving their original case (v3.0.0) — declarations were
 * lowercased, references were not, so every aliased token produced a dangling
 * `var()`. See VMLYR/token-forge#60.
 */

import { describe, test, expect } from 'vitest';
import {
  CSSFormatExporter,
  toCSSVariableName,
} from '../../src/plugin/format-exporters/css-exporter';
import { DTCGFile } from '../../src/types/dtcg';
import { FormatOptions } from '../../src/types/export-formats';

/** Collects the `--name` of every declaration in a stylesheet. */
function declaredVars(css: string): Set<string> {
  const names = new Set<string>();
  const re = /^\s*--([^:\s]+)\s*:/gm;
  let m: RegExpExecArray | null;
  while ((m = re.exec(css)) !== null) {
    names.add(m[1]);
  }
  return names;
}

/** Collects the `--name` of every `var()` reference in a stylesheet. */
function referencedVars(css: string): string[] {
  const names: string[] = [];
  const re = /var\(--([^)\s,]+)/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(css)) !== null) {
    names.push(m[1]);
  }
  return names;
}

function dangling(css: string): string[] {
  const declared = declaredVars(css);
  return referencedVars(css).filter(name => !declared.has(name));
}

const options = (prefix?: string): FormatOptions => ({
  format: 'css',
  config: { css: Object.assign({ useCustomProperties: true }, prefix ? { prefix } : {}) },
});

/**
 * A file exercising every alias-bearing code path in the exporter: color,
 * dimension (object + string form), generic (fontFamily/number), typography
 * sub-properties, and shadow dimensions. Token names deliberately use the
 * camelCase that v3.0.0 now preserves.
 */
const tokens: DTCGFile = {
  palette: {
    onSuccessContainer: {
      $type: 'color',
      $value: { colorSpace: 'srgb', components: [0, 1, 0] },
    },
  },
  color: {
    bgPrimary: { $type: 'color', $value: '{palette.onSuccessContainer}' },
  },
  spacing: {
    baseSize: { $type: 'dimension', $value: { value: 4, unit: 'px' } },
    gapLarge: { $type: 'dimension', $value: '{spacing.baseSize}' },
  },
  font: {
    displayFamily: { $type: 'fontFamily', $value: 'Inter' },
    headingFamily: { $type: 'fontFamily', $value: '{font.displayFamily}' },
    baseWeight: { $type: 'number', $value: 400 },
    boldWeight: { $type: 'number', $value: '{font.baseWeight}' },
  },
  typography: {
    displayLarge: {
      $type: 'typography',
      $value: {
        fontFamily: '{font.displayFamily}',
        fontSize: { value: 32, unit: 'px' },
        fontWeight: '{font.baseWeight}',
        lineHeight: 1.2,
      },
    },
  },
  shadow: {
    cardRaised: {
      $type: 'shadow',
      $value: [
        {
          offsetX: '{spacing.baseSize}',
          offsetY: { value: 2, unit: 'px' },
          blur: '{spacing.baseSize}',
          color: { colorSpace: 'srgb', components: [0, 0, 0], alpha: 0.1 },
        },
      ],
    },
  },
};

describe('toCSSVariableName', () => {
  test('splits camelCase humps, matching SD name/cti/kebab', () => {
    expect(toCSSVariableName('color.onSuccessContainer')).toBe('color-on-success-container');
    expect(toCSSVariableName('spacing.baseSize')).toBe('spacing-base-size');
  });

  test('handles acronym boundaries', () => {
    expect(toCSSVariableName('util.parseHTMLValue')).toBe('util-parse-html-value');
  });

  test('produces the same identifier from a dotted path and a hyphenated one', () => {
    // The declaration side passes a "." path; the reference side passes an
    // alias's inner text. Both must land on the same ident.
    expect(toCSSVariableName('a.bCd')).toBe(toCSSVariableName('a-bCd'));
  });

  test('is idempotent', () => {
    const once = toCSSVariableName('color.onSuccessContainer');
    expect(toCSSVariableName(once)).toBe(once);
  });

  test('collapses characters that are unsafe in a custom-property ident', () => {
    expect(toCSSVariableName('color.on Success')).toBe('color-on-success');
    expect(toCSSVariableName('color.brand+accent')).toBe('color-brand-accent');
  });

  test('applies the prefix verbatim', () => {
    expect(toCSSVariableName('color.bg', 'ds-')).toBe('ds-color-bg');
  });
});

describe('CSS declaration/reference symmetry', () => {
  test('every var() reference has a matching declaration', async () => {
    const [out] = await new CSSFormatExporter().export(tokens, options());
    expect(dangling(out.content)).toEqual([]);
  });

  test('references resolve when a prefix is configured', async () => {
    // Regression: the prefix was applied to declarations only, so every
    // reference pointed at an unprefixed name that was never declared.
    const [out] = await new CSSFormatExporter().export(tokens, options('ds-'));
    expect(dangling(out.content)).toEqual([]);
    expect(out.content).toContain('--ds-color-bg-primary:');
    expect(out.content).toContain('var(--ds-palette-on-success-container)');
  });

  test('preserved-case names emit hyphenated CSS idents, not flattened ones', async () => {
    const [out] = await new CSSFormatExporter().export(tokens, options());
    expect(out.content).toContain('--palette-on-success-container:');
    expect(out.content).not.toContain('onsuccesscontainer');
    expect(out.content).not.toContain('onSuccessContainer');
  });

  test('the fixture actually exercises the reference path', async () => {
    // Guards against the symmetry assertions passing vacuously if the fixture
    // or the exporter stops emitting aliases at all.
    const [out] = await new CSSFormatExporter().export(tokens, options());
    expect(referencedVars(out.content).length).toBeGreaterThanOrEqual(6);
  });

  test('shadow shorthand aliases resolve too', async () => {
    const [out] = await new CSSFormatExporter().export(tokens, options());
    expect(out.content).toContain('--shadow-card-raised:');
    expect(out.content).toContain('var(--spacing-base-size)');
  });

  test('expanded typography properties reference declared tokens', async () => {
    const [out] = await new CSSFormatExporter().export(tokens, options());
    expect(out.content).toContain('--typography-display-large-font-family:');
    expect(out.content).toContain('var(--font-display-family)');
  });

  test('utility-class output uses the same identifier builder', async () => {
    // Symmetry is deliberately NOT asserted here: the utility branch emits no
    // ":root" block, so its aliased tokens reference custom properties that
    // this output never declares. That is a pre-existing gap in a branch the UI
    // cannot reach (generateUtilities is hardcoded false in src/code.ts), not
    // something the casing change introduced. What matters for this fix is that
    // class names and references come from the one shared ident builder.
    const [out] = await new CSSFormatExporter().export(tokens, {
      format: 'css',
      config: { css: { useCustomProperties: false, generateUtilities: true } },
    });
    expect(out.content).toContain('.palette-on-success-container {');
    expect(out.content).toContain('var(--palette-on-success-container)');
    expect(declaredVars(out.content).size).toBe(0);
  });
});
