/**
 * The "used by" index (UI redesign S7, technical call T4): which of the engine's component definitions bind each
 * radius size and each control height, written out as DATA for the Shape preview and the Style guide's radius
 * sample to read.
 *
 *   npx tsx apps/studio/gen-used-by.ts --write    # rewrite src/preview/used-by.ts from the definitions
 *   npx tsx apps/studio/test-used-by.ts           # (in `npm test`) fail when the committed index is stale
 *
 * WHY DATA AND NOT AN IMPORT. The web bundle never imports the component definitions: one reference to
 * `componentDefs`, gated or not, puts definitions' prose into `apps/studio/dist` (the component catalog's own
 * reasoning in `src/state/component-catalog.ts`, `vercel-ignore-check.mjs`, and `lint-bundle-prose`'s intent).
 * `button-spacing.ts` is the engine's precedent for the same need. So the studio
 * reads a small generated table instead, and `test-used-by.ts` holds it to the definitions it was written from.
 *
 * WHAT IT COUNTS. A definition uses a radius size when one of its `tokens` values is `radius.<size>`, and a control
 * height when one is `size.<step>.height`. Radius is counted once per Control shape: `applyControlShape` (the
 * engine's own materialization, the one the Figma build runs) repoints a pill-able control's rounded radius, so
 * which definitions use `radius.md`, `radius.capsule`, `radius.none` or `radius.hairline` depends on the brand's
 * shape. Names are the definitions' own, with a definition's intent variants folded into it (`Button.Destructive`
 * reads as `Button`) when the part before the dot is itself a definition.
 *
 * `buttonSizes` names each control height the Button definition binds by its size key (`size.medium.height` →
 * `Medium`), for the Density preview's "Medium button · 44px" (owner decision D6).
 */
import { writeFileSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { componentDefs } from '@prism3/engine/components/index';
import { applyControlShape } from '@prism3/engine/anatomy-figma';
import type { ControlShape } from '@prism3/engine/scale';

export const OUT = join(dirname(fileURLToPath(import.meta.url)), 'src', 'preview', 'used-by.ts');
const SHAPES: readonly ControlShape[] = ['rounded', 'pill', 'boxed', 'hairline'];

export type UsedByIndex = {
  defs: number;
  radius: Record<string, Record<string, string[]>>;
  height: Record<string, string[]>;
  buttonSizes: Record<string, string>;
};

/** The index, computed from the definitions. */
export const computeUsedBy = (): UsedByIndex => {
  const names = new Set(componentDefs.map((d) => d.name));
  const family = (n: string): string => { const base = n.split('.')[0]; return base !== n && names.has(base) ? base : n; };
  const refs = (tokens: Record<string, unknown>, re: RegExp): string[] => Object.values(tokens).filter((v): v is string => typeof v === 'string' && re.test(v));
  const add = (m: Record<string, string[]>, k: string, n: string): void => { const l = (m[k] ??= []); if (!l.includes(n)) l.push(n); };
  const radius: Record<string, Record<string, string[]>> = {};
  for (const shape of SHAPES) {
    const m: Record<string, string[]> = {};
    for (const d of componentDefs) for (const r of refs(applyControlShape(d, shape).tokens as Record<string, unknown>, /^radius\.[a-z0-9]+$/)) add(m, r, family(d.name));
    radius[shape] = Object.fromEntries(Object.keys(m).sort().map((k) => [k, m[k]]));
  }
  const hm: Record<string, string[]> = {};
  for (const d of componentDefs) for (const r of refs(d.tokens as Record<string, unknown>, /^size\.[a-z0-9]+\.height$/)) add(hm, r, family(d.name));
  const height = Object.fromEntries(Object.keys(hm).sort().map((k) => [k, hm[k]]));
  const button = componentDefs.find((d) => d.id === 'button');
  const buttonSizes: Record<string, string> = {};
  for (const [k, v] of Object.entries(button?.tokens ?? {})) {
    const m = /^size\.([a-z]+)\.height$/.exec(k);
    if (m && typeof v === 'string') buttonSizes[v] = `${m[1][0].toUpperCase()}${m[1].slice(1)}`;
  }
  return { defs: componentDefs.length, radius, height, buttonSizes };
};

/** The module text for an index. */
export const render = (ix: UsedByIndex): string => `/**
 * GENERATED by \`apps/studio/gen-used-by.ts\` from the engine's component definitions. Do not edit by hand: run
 * \`npx tsx apps/studio/gen-used-by.ts --write\`. \`test-used-by.ts\` fails while this file is stale.
 *
 * Which definitions bind each radius size (per Control shape) and each control height, as data, so the web bundle
 * never imports the definitions themselves (UI redesign S7, T4; the generator's header says why).
 */
export const USED_BY = ${JSON.stringify(ix, null, 2).replace(/"([a-zA-Z][a-zA-Z0-9]*)":/g, '$1:')} as const;
`;

if (process.argv.includes('--write')) {
  const text = render(computeUsedBy());
  let was = '';
  try { was = readFileSync(OUT, 'utf8'); } catch { /* first write */ }
  if (was === text) console.log(`${OUT}: unchanged`);
  else { writeFileSync(OUT, text); console.log(`${OUT}: written`); }
}
