/**
 * The web's component catalog (UI redesign S8.1, technical call T1): every component set the engine defines, with
 * whether it builds, its member count and unit, the sets it nests, its category and its one-line summary, written out
 * as DATA for the web build to read.
 *
 *   npx tsx apps/studio/gen-component-catalog.ts --write   # rewrite src/state/component-catalog-data.ts
 *   npx tsx apps/studio/test-component-catalog.ts          # (in `npm test`) fail when the committed data is stale
 *
 * WHY DATA AND NOT AN IMPORT. The web bundle never imports the component definitions: one reference to
 * `componentDefs` puts their prose into `apps/studio/dist` (about 35 KB gzip). `gen-used-by.ts` is the studio's
 * precedent for the same need. The plugin bundles the definitions anyway and computes the same catalog live
 * (`apps/plugin/src/ui/component-catalog.ts`); this writes the web's copy with the same function
 * (`state/component-catalog.ts`'s `catalogOf`), and `test-component-catalog.ts` holds the copy to the
 * definitions and to the projector, run independently.
 */
import { writeFileSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { componentDefs } from '@prism3/engine/components/index';
import { figmaAnatomySet } from '@prism3/engine/anatomy-figma';
import { catalogOf, CATALOG_SWAP_TARGET, type CatalogEntry } from './src/state/component-catalog';

export const OUT = join(dirname(fileURLToPath(import.meta.url)), 'src', 'state', 'component-catalog-data.ts');

/** The catalog, computed from the definitions. */
export const computeCatalog = (): CatalogEntry[] =>
  catalogOf(componentDefs, (d) => figmaAnatomySet(d, { swapTarget: CATALOG_SWAP_TARGET }));

/** The module text for a catalog. */
export const render = (c: readonly CatalogEntry[]): string => `/**
 * GENERATED by \`apps/studio/gen-component-catalog.ts\` from the engine's component definitions. Do not edit by hand:
 * run \`npx tsx apps/studio/gen-component-catalog.ts --write\`. \`test-component-catalog.ts\` fails while this file
 * is stale.
 *
 * The component catalog as data, so the web bundle never imports the definitions themselves (UI redesign S8.1, T1;
 * the generator's header says why). The plugin computes the same catalog live.
 */
import type { Catalog } from './component-catalog';

export const COMPONENT_CATALOG_DATA: Catalog = ${JSON.stringify(c, null, 2)};
`;

if (process.argv.includes('--write')) {
  const text = render(computeCatalog());
  let was = '';
  try { was = readFileSync(OUT, 'utf8'); } catch { /* first write */ }
  if (was === text) console.log(`${OUT}: unchanged`);
  else { writeFileSync(OUT, text); console.log(`${OUT}: written`); }
}
