/**
 * Prism3 engine — THE ICON VOCABULARY (`docs/40` §5.3, closing #833).
 *
 * **AUTHORED, never generated.** This file maps OUR glyph names to the source filenames in
 * `icons/`. It is the one place a human decides what a glyph is called, and it is deliberately not
 * derived from the directory — a mapping generated by scanning the thing it maps would agree with
 * that directory by construction and could never disagree with it, which is the whole point of
 * having it (`docs/34` shape 1).
 *
 * ── WHY OUR NAMES RATHER THAN THE SOURCE'S ──────────────────────────────────────────────────────
 *
 * `icon.name` is part of the versioned component name surface (#823): a consumer writes
 * `<Icon name="chevron-down" />` and a rename resolves to nothing with no error anywhere. Adopting
 * Remix Icon's vocabulary as our contract would hand the stability of our public names to a third
 * party, and would make replacing the set a MAJOR break rather than a mapping edit.
 *
 * The set is explicitly a **placeholder core, intended to be swapped for a client's branded set**
 * (`icons/NOTICE.md` — that intent is also the licence argument, so it is written down rather than
 * remembered). Swapping it changes this file and the SVGs beside it. Nothing downstream moves.
 *
 * Source names are opaque in a way that is easy to underestimate: Remix's chevrons are
 * `arrow-*-s-line`, its check-in-a-circle is `checkbox-circle-line` (it is not a checkbox), and its
 * exclamation-in-a-circle is `error-warning-line`. A consumer would not guess any of the three.
 *
 * ── THE `-filled` SUFFIX, AND A WART WE ARE KEEPING RATHER THAN HIDING ───────────────────────────
 *
 * Line style is NOT an axis. 39 files are 29 concepts and only 10 carry both styles, so an
 * `icon.style: line | fill` variant would be undefined for 19 of 29 — an axis whose members do not
 * all exist, which is #795's trap one tier down. The style therefore lives in the NAME: the line
 * form is unsuffixed and the filled form takes `-filled`.
 *
 * The filled form is always suffixed **even where it has no line sibling** (`more-horizontal`,
 * `more-vertical`). Naming those bare would mean renaming them the day a line variant arrives, and a
 * rename is the one thing this file exists to prevent.
 *
 * **The wart, MEASURED — and it is worse than the earlier reading of it.** For glyphs that are pure
 * strokes there is no filled shape to draw, so the source set has nothing to put under `-fill`. This
 * paragraph used to say the `-fill` was a HEAVIER WEIGHT ("`close-filled` is a bolder X"). That was
 * an assumption, and #864 measured it false for all three of them:
 *
 *   · `add-line.svg` and `add-fill.svg` are **byte-identical** (sha256 `e3af16eef67d`, 177 bytes).
 *   · `close-line.svg` and `close-fill.svg` are **byte-identical** (sha256 `2d004b029720`, 345 bytes).
 *   · `subtract-line.svg` and `subtract-fill.svg` differ by exactly the winding of one rectangle —
 *     `M5 11V13H19V11H5Z` against `M19 11H5V13H19V11Z`. Same 14×2 ink box, same pixels.
 *
 * So `plus-filled` and `plus` render the same glyph, as do `close-filled`/`close` and
 * `minus-filled`/`minus`: **6 of the 39 names are 3 distinct shapes**, and the vocabulary holds 37
 * distinct paths rather than 39. That is not a mapping error — each name resolves to the file it
 * claims — so `emit-icons.ts`, which compares both directions of *filenames*, structurally cannot
 * see it. It is a provenance defect in the source set, filed as #917.
 *
 * We keep the names rather than deleting three of them, because dropping a name from `icon.name` is a
 * MAJOR contract break to fix a cosmetic duplication, and because a branded set swapped in later may
 * well draw all six distinctly. What is corrected here is the *claim*: they are duplicates, not bolder
 * variants. Anyone reasoning about `-filled` as a weight axis would be reasoning from a shape that is
 * not there.
 *
 * ── ADDING OR REMOVING A GLYPH ──────────────────────────────────────────────────────────────────
 *
 * Drop the `.svg` in `icons/` and add a line here. `emit-icons.ts` checks BOTH directions and fails
 * on either half: a file with no mapping entry, and an entry naming no file. Neither is a warning —
 * a silently unmapped glyph is invisible in exactly the way `icon.name`'s own prop description says
 * a missing glyph must never be.
 *
 * Adding a name is a MINOR contract bump; removing or renaming one is MAJOR. See
 * `docs/30-versioning-and-compatibility.md`.
 */

/** Our glyph name → the source filename in `icons/` (without the `.svg`). */
export const ICON_SOURCES: Record<string, string> = {
  // ── arrows and chevrons ───────────────────────────────────────────────────────────────────────
  // Remix's `-s-` forms are the chevrons; the bare forms are full arrows. The two read almost
  // identically in the source vocabulary and do completely different jobs in a UI.
  'chevron-down': 'arrow-down-s-line',
  'chevron-up': 'arrow-up-s-line',
  'chevron-left': 'arrow-left-s-line',
  'chevron-right': 'arrow-right-s-line',
  'arrow-down': 'arrow-down-line',
  'arrow-up': 'arrow-up-line',
  'arrow-left': 'arrow-left-line',
  'arrow-right': 'arrow-right-line',
  'arrow-up-left': 'arrow-left-up-line',
  'arrow-up-right': 'arrow-right-up-line',
  'arrow-down-left': 'arrow-left-down-line',
  'arrow-down-right': 'arrow-right-down-line',

  // ── control glyphs ────────────────────────────────────────────────────────────────────────────
  // `check` and `minus` are the checkbox's two marks — checked and indeterminate. `minus` is
  // Remix's `subtract`, which reads as an operation rather than a mark.
  check: 'check-line',
  minus: 'subtract-line',
  'minus-filled': 'subtract-fill',
  plus: 'add-line',
  'plus-filled': 'add-fill',
  'plus-circle': 'add-circle-line',
  'plus-circle-filled': 'add-circle-fill',
  close: 'close-line',
  'close-filled': 'close-fill',

  // ── status ────────────────────────────────────────────────────────────────────────────────────
  // The four status glyphs, and the reason both styles are kept: status is colour AND icon, never
  // colour alone, and the filled form is the field convention for a status indicator in a banner or
  // toast (Primer, Carbon, Material all do this). `banner` and `field-message` are both in
  // `docs/40`'s tranche 2.
  'info-circle': 'information-line',
  'info-circle-filled': 'information-fill',
  'check-circle': 'checkbox-circle-line',
  'check-circle-filled': 'checkbox-circle-fill',
  'warning-triangle': 'alert-line',
  'warning-triangle-filled': 'alert-fill',
  'error-circle': 'error-warning-line',
  'error-circle-filled': 'error-warning-fill',

  // ── field and menu affordances ────────────────────────────────────────────────────────────────
  // `eye` / `eye-off` is the password-reveal toggle — a `text-field` need `docs/40`'s glyph census
  // missed entirely, and one of three glyphs that arrived beyond what was asked for.
  eye: 'eye-line',
  'eye-filled': 'eye-fill',
  'eye-off': 'eye-off-line',
  'eye-off-filled': 'eye-off-fill',
  // Remix's `more-2` is the VERTICAL ellipsis and bare `more` is the horizontal one. Nothing in
  // either filename says so; it was confirmed by looking at them.
  'more-horizontal-filled': 'more-fill',
  'more-vertical-filled': 'more-2-fill',
  home: 'home-line',

  // Landed in #841 concurrently with this file's authoring; mapped here rather than left
  // unreachable. `link-m` keeps its source filename rather than renaming to `link-line` — #841's own
  // call, since the artwork is line-weight by every other icon's convention and a rename after
  // `icon.name` ships is the MAJOR break this file exists to avoid.
  search: 'search-line',
  link: 'link-m',
  'external-link-filled': 'external-link-fill',
};

/** Every glyph name this engine defines — the literal vocabulary `icon.name` is typed against. */
export type IconName = keyof typeof ICON_SOURCES;
