/**
 * Prism3 engine — THE ICON VOCABULARY (`docs/40` §5.3, closing #833).
 *
 * **AUTHORED, never generated.** This file maps OUR glyph names to the source filenames in
 * `icons/`. It is the one place a human decides what a glyph is called, and it is deliberately not
 * derived from the directory — a mapping generated by scanning the thing it maps would agree with
 * that directory by construction and could never disagree with it, which is the whole point of
 * having it (`docs/34` shape 1).
 *
 * ── WHY OUR NAMES RATHER THAN THE SOURCE'S ──────────────────────────────────────────────────────
 *
 * `icon.name` is part of the versioned component name surface (#823): a consumer writes
 * `<Icon name="chevron-down" />` and a rename resolves to nothing with no error anywhere. Adopting
 * Remix Icon's vocabulary as our contract would hand the stability of our public names to a third
 * party, and would make replacing the set a MAJOR break rather than a mapping edit.
 *
 * The set is explicitly a **placeholder core, intended to be swapped for a client's branded set**
 * (`icons/NOTICE.md` — that intent is also the licence argument, so it is written down rather than
 * remembered). Swapping it changes this file and the SVGs beside it. Nothing downstream moves.
 *
 * Source names are opaque in a way that is easy to underestimate: Remix's chevrons are
 * `arrow-*-s-line`, its check-in-a-circle is `checkbox-circle-line` (it is not a checkbox), and its
 * exclamation-in-a-circle is `error-warning-line`. A consumer would not guess any of the three.
 *
 * ── THE `-filled` SUFFIX, AND A WART WE ARE KEEPING RATHER THAN HIDING ───────────────────────────
 *
 * Line style is NOT an axis. 40 files are 30 concepts and only 10 carry both styles, so an
 * `icon.style: line | fill` variant would be undefined for 20 of 30 — an axis whose members do not
 * all exist, which is #795's trap one tier down. The style therefore lives in the NAME: the line
 * form is unsuffixed and the filled form takes `-filled`.
 *
 * The filled form is always suffixed **even where it has no line sibling** (`more-horizontal`,
 * `more-vertical`). Naming those bare would mean renaming them the day a line variant arrives, and a
 * rename is the one thing this file exists to prevent.
 *
 * **The wart, MEASURED — and it is worse than the earlier reading of it.** For glyphs that are pure
 * strokes there is no filled shape to draw, so the source set has nothing to put under `-fill`. This
 * paragraph used to say the `-fill` was a HEAVIER WEIGHT ("`close-filled` is a bolder X"). That was
 * an assumption, and #864 measured it false for all three of them:
 *
 *   · `add-line.svg` and `add-fill.svg` are **byte-identical** (sha256 `e3af16eef67d`, 177 bytes).
 *   · `close-line.svg` and `close-fill.svg` are **byte-identical** (sha256 `2d004b029720`, 345 bytes).
 *   · `subtract-line.svg` and `subtract-fill.svg` are the SAME RECTANGLE STARTED AT A DIFFERENT
 *     VERTEX — `M5 11V13H19V11H5Z` against `M19 11H5V13H19V11Z`. Same 14×2 ink box, same pixels.
 *
 * So `plus-filled` and `plus` render the same glyph, as do `close-filled`/`close` and
 * `minus-filled`/`minus`: **6 of the 40 names are 3 distinct shapes**, and the vocabulary holds 38
 * distinct paths across its 40 names (the shape-distinct `FPO-default-icon` is the 40th). That is not a
 * mapping error — each name resolves to the file it claims — so `emit-icons.ts`, which compares both
 * directions of *filenames*, structurally cannot see it. Filed as #917.
 *
 * **#917 corrected the third line above, and the correction matters more than it looks.** This file
 * said the subtract pair "differ by exactly the winding of one rectangle", and #917's own body repeated
 * it. Measured: both rings run (5,11) → (5,13) → (19,13) → (19,11), in the SAME direction; `-fill`
 * merely begins at (19,11). Rotation alone merges them and reversal alone does not, so `fill-rule`
 * never enters into it — a reader who believed the winding story would reach for the wrong fix.
 *
 * ── AND WHY THERE IS NO SOURCE FIX, MEASURED IN #917 RATHER THAN ASSUMED ─────────────────────────
 *
 * `-filled` in this set means the SOLID, ENCLOSED form, and that is measurable rather than a matter of
 * taste. Rasterizing each pair at 4× over the 24×24 viewBox with nonzero winding and taking the ratio
 * of inked area, `fill` ÷ `line`:
 *
 *     add-circle 1.86×   alert 1.61×   checkbox-circle 2.01×   error-warning 2.30×
 *     eye 1.57×          eye-off 1.38×   information 2.30×
 *     ────────────────────────────────────────────────────────────────
 *     add 1.00×          close 1.00×     subtract 1.00×
 *
 * Every one of the seven genuine pairs lands between 1.38× and 2.30×. The three defects land at exactly
 * 1.00×, and they are exactly the glyphs with no interior: a plus, an X and a dash are bare strokes,
 * with nothing enclosed for a fill to fill. **The source set is not wrong here — it declined to invent
 * a shape, which is the correct call.** So the two available "fixes" are both worse than the wart:
 * inventing a heavier-weight variant is precisely the reading #864 measured false as the meaning of
 * `-fill`, and borrowing the circled forms collides with names that already exist (`plus-circle-filled`
 * → `add-circle-fill`) while adding an enclosure the name does not mention.
 *
 * We therefore keep all 40 names. Dropping one is a MAJOR contract break to fix a cosmetic duplication,
 * and a branded set swapped in later may well draw all six distinctly — `docs/40` §5.3 now states that
 * as a delivery constraint, which is the durable fix. What is corrected here is the *claim*: they are
 * duplicates, not bolder variants. Anyone reasoning about `-filled` as a weight axis would be reasoning
 * from a shape that is not there.
 *
 * The duplication is now CHECKED rather than only described: `lint-glyph-geometry.ts` compares rendered
 * shape via `glyph-shape.ts` and fails on any collision not declared in its `DUPLICATE_SHAPES`, in both
 * directions. A fourth pair appearing, or one of these three starting to differ, fails by name.
 *
 * ── ADDING OR REMOVING A GLYPH ──────────────────────────────────────────────────────────────────
 *
 * Drop the `.svg` in `icons/` and add a line here. `emit-icons.ts` checks BOTH directions and fails
 * on either half: a file with no mapping entry, and an entry naming no file. Neither is a warning —
 * a silently unmapped glyph is invisible in exactly the way `icon.name`'s own prop description says
 * a missing glyph must never be.
 *
 * Adding a name is a MINOR contract bump; removing or renaming one is MAJOR. See
 * `docs/30-versioning-and-compatibility.md`.
 */

/** Our glyph name → the source filename in `icons/` (without the `.svg`). */
export const ICON_SOURCES: Record<string, string> = {
  // ── arrows and chevrons ───────────────────────────────────────────────────────────────────────
  // Remix's `-s-` forms are the chevrons; the bare forms are full arrows. The two read almost
  // identically in the source vocabulary and do completely different jobs in a UI.
  'chevron-down': 'arrow-down-s-line',
  'chevron-up': 'arrow-up-s-line',
  'chevron-left': 'arrow-left-s-line',
  'chevron-right': 'arrow-right-s-line',
  'arrow-down': 'arrow-down-line',
  'arrow-up': 'arrow-up-line',
  'arrow-left': 'arrow-left-line',
  'arrow-right': 'arrow-right-line',
  'arrow-up-left': 'arrow-left-up-line',
  'arrow-up-right': 'arrow-right-up-line',
  'arrow-down-left': 'arrow-left-down-line',
  'arrow-down-right': 'arrow-right-down-line',

  // ── control glyphs ────────────────────────────────────────────────────────────────────────────
  // `check` and `minus` are the checkbox's two marks — checked and indeterminate. `minus` is
  // Remix's `subtract`, which reads as an operation rather than a mark.
  check: 'check-line',
  minus: 'subtract-line',
  'minus-filled': 'subtract-fill',
  plus: 'add-line',
  'plus-filled': 'add-fill',
  'plus-circle': 'add-circle-line',
  'plus-circle-filled': 'add-circle-fill',
  close: 'close-line',
  'close-filled': 'close-fill',

  // ── status ────────────────────────────────────────────────────────────────────────────────────
  // The four status glyphs, and the reason both styles are kept: status is colour AND icon, never
  // colour alone, and the filled form is the field convention for a status indicator in a banner or
  // toast (Primer, Carbon, Material all do this). `banner` and `field-message` are both in
  // `docs/40`'s tranche 2.
  'info-circle': 'information-line',
  'info-circle-filled': 'information-fill',
  'check-circle': 'checkbox-circle-line',
  'check-circle-filled': 'checkbox-circle-fill',
  'warning-triangle': 'alert-line',
  'warning-triangle-filled': 'alert-fill',
  'error-circle': 'error-warning-line',
  'error-circle-filled': 'error-warning-fill',

  // ── field and menu affordances ────────────────────────────────────────────────────────────────
  // `eye` / `eye-off` is the password-reveal toggle — a `text-field` need `docs/40`'s glyph census
  // missed entirely, and one of three glyphs that arrived beyond what was asked for.
  eye: 'eye-line',
  'eye-filled': 'eye-fill',
  'eye-off': 'eye-off-line',
  'eye-off-filled': 'eye-off-fill',
  // Remix's `more-2` is the VERTICAL ellipsis and bare `more` is the horizontal one. Nothing in
  // either filename says so; it was confirmed by looking at them.
  'more-horizontal-filled': 'more-fill',
  'more-vertical-filled': 'more-2-fill',
  home: 'home-line',

  // Landed in #841 concurrently with this file's authoring; mapped here rather than left
  // unreachable. `link-m` keeps its source filename rather than renaming to `link-line` — #841's own
  // call, since the artwork is line-weight by every other icon's convention and a rename after
  // `icon.name` ships is the MAJOR break this file exists to avoid.
  search: 'search-line',
  link: 'link-m',
  'external-link-filled': 'external-link-fill',

  // ── placeholder ───────────────────────────────────────────────────────────────────────────────
  // The FPO ("for placement only") default glyph — a lettered disc shown wherever a name has not been
  // chosen yet, so an unresolved icon reads as DELIBERATELY unset rather than as a missing asset. It is
  // the 40th member of the vocabulary and a real, nameable `icon/FPO-default-icon`, not a fallback that
  // lives outside the set. It is also the FIRST glyph whose source declares `fill-rule="evenodd"`: the
  // "FPO" letters are knocked out of the disc, which nonzero winding would fill back in solid. That is a
  // real, reusable pipeline gap the placeholder forced open (#1012) — `emit-icons.ts` now preserves the
  // attribute and `icon-glyphs.ts` carries it in `ICON_FILL_RULES`. Not the winding story #917 warns
  // against on the subtract pair: this glyph genuinely relies on even-odd, and the source declares it.
  'FPO-default-icon': 'fpo-default-icon',
};

/** Every glyph name this engine defines — the literal vocabulary `icon.name` is typed against. */
export type IconName = keyof typeof ICON_SOURCES;
