/**
 * GENERATED by `apps/studio/gen-used-by.ts` from the engine's component definitions. Do not edit by hand: run
 * `npx tsx apps/studio/gen-used-by.ts --write`. `test-used-by.ts` fails while this file is stale.
 *
 * Which definitions bind each radius size (per Control shape) and each control height, as data, so the web bundle
 * never imports the definitions themselves (UI redesign S7, T4; the generator's header says why).
 */
export const USED_BY = {
  defs: 29,
  radius: {
    rounded: {
      "radius.md": [
        "Button",
        "IconButton"
      ],
      "radius.round": [
        "IconButton",
        "Radio.Control",
        "Switch.Control",
        "Badge",
        "Tag"
      ],
      "radius.sm": [
        "TextField",
        "Textarea",
        "Select",
        "Badge"
      ]
    },
    pill: {
      "radius.capsule": [
        "Button",
        "IconButton"
      ],
      "radius.round": [
        "IconButton",
        "Radio.Control",
        "Switch.Control",
        "Badge",
        "Tag"
      ],
      "radius.sm": [
        "TextField",
        "Textarea",
        "Select",
        "Badge"
      ]
    },
    boxed: {
      "radius.none": [
        "Button",
        "IconButton",
        "TextField",
        "Textarea",
        "Checkbox.Control",
        "Select"
      ],
      "radius.round": [
        "IconButton",
        "Radio.Control",
        "Switch.Control",
        "Badge",
        "Tag"
      ],
      "radius.sm": [
        "Badge"
      ]
    },
    hairline: {
      "radius.hairline": [
        "Button",
        "IconButton",
        "TextField",
        "Textarea",
        "Checkbox.Control",
        "Select"
      ],
      "radius.round": [
        "IconButton",
        "Radio.Control",
        "Switch.Control",
        "Badge",
        "Tag"
      ],
      "radius.sm": [
        "Badge"
      ]
    }
  },
  height: {
    "size.lg.height": [
      "Button",
      "IconButton",
      "TextField",
      "Checkbox.Row",
      "Radio.Row",
      "Select",
      "Tag",
      "Tab"
    ],
    "size.md.height": [
      "FocusRing",
      "Button",
      "IconButton",
      "Checkbox.Row",
      "Radio.Row",
      "Switch.Row",
      "Tag",
      "Tab",
      "Divider"
    ],
    "size.sm.height": [
      "Button",
      "IconButton",
      "Checkbox.Row",
      "Radio.Row",
      "Switch.Row",
      "Tag",
      "Tab"
    ]
  },
  buttonSizes: {
    "size.sm.height": "Small",
    "size.md.height": "Medium",
    "size.lg.height": "Large"
  }
} as const;
